{% set name = "beavers" %}
{% set version = "0.14.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/beavers-{{ version }}.tar.gz
  sha256: d84abc57cad0311ddc2bc6a43550572c787015454bc10cc0a99f0e871791fa52

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core
    - poetry-dynamic-versioning
    - pip
  run:
    - python >={{ python_min }}
    - python-confluent-kafka >=2.1.1
    - pandas >1.4.0
    - perspective-python >=3.0.0
    - polars
    - pyarrow >=12.0
    - tornado

test:
  imports:
    - beavers
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/tradewelltech/beavers
  summary: Python stream processing
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - 0x26res
